# frozen_string_literal: true

require 'spec_helper'

RSpec.describe Integrate::Generator::Service do
  subject(:service) { described_class.new(spec) }

  let(:spec) { Integrate::Parser::OpenApi.new(SpecPaths::NOVAPAY).parse }
  let(:generated) { service.call }

  it 'declares Provider::NovapayService < BaseService' do
    expect(generated).to include('class Provider')
    expect(generated).to include('class NovapayService < BaseService')
  end

  it 'sets BASE_URL from the first server' do
    expect(generated).to include(
      "BASE_URL = ENV.fetch('NOVAPAY_BASE_URL', 'https://api.sandbox.novapay.example/v1')"
    )
  end

  it 'renders create_request with idempotency + rescue blocks' do
    expect(generated).to include('def create_request(operation, request_method = \'create\')')
    expect(generated).to include('Idempotency-Key')
    expect(generated).to include('rescue Provider::RateLimitError')
    expect(generated).to include('rescue Provider::UnauthorizedError')
  end

  it 'renders fetch_status using operation.provider_operation_id' do
    expect(generated).to include('def fetch_status(operation)')
    expect(generated).to include('/payouts/#{operation.provider_operation_id}')
    expect(generated).to include('map_status(response.body[\'status\'])')
  end

  it 'renders process_callback with case-per-event' do
    # Uses regex-based case to support both NovaPay-style ('payout.completed')
    # and PayCloud/Stripe-style ('transfer.settled') without provider hardcoding.
    expect(generated).to match(%r{when /completed\$.*settled\$.*paid\$.*succeeded\$/})
    expect(generated).to match(%r{when /failed\$.*declined\$.*rejected\$/})
    expect(generated).to include('approve_operation(payload[\'payout_id\'])')
    expect(generated).to include('reject_operation(payload[\'payout_id\']')
    expect(generated).to include("event = payload['event'] || payload['type']")
  end

  it 'renders check_conditions with amount-too-low guard' do
    expect(generated).to include('def check_conditions(operation, request_method)')
    expect(generated).to include('operation.amount < 1000')
  end

  it 'renders cancel_request and fetch_balance helpers' do
    expect(generated).to include('def cancel_request(operation)')
    expect(generated).to include('def fetch_balance')
  end

  it 'includes STATUS_MAP with all 5 NovaPay statuses' do
    %w[pending processing completed failed cancelled].each do |st|
      expect(generated).to include("'#{st}'")
    end
    expect(generated).to include("'approved'")
    expect(generated).to include("'rejected'")
  end

  it 'includes ERROR_MAP with declared HTTP codes' do
    expect(generated).to include('ERROR_MAP = {')
    [400, 401, 402, 422, 429, 500].each do |code|
      expect(generated).to include("#{code} =>")
    end
  end

  it 'includes PROVIDER_ERROR_MAP built from the PayoutError enum' do
    expect(generated).to include('PROVIDER_ERROR_MAP = {')
    expect(generated).to include("'rate_limit_exceeded' => 'rate_limit'")
    expect(generated).to include("'insufficient_balance'")
  end

  it 'renders auth_headers under the API key scheme' do
    expect(generated).to include("{ 'X-API-Key' => credentials.fetch('api_key') }")
  end

  it 'renders build_payout_payload with amount in minor units and SBP recipient' do
    expect(generated).to include('def build_payout_payload(operation)')
    expect(generated).to include('(operation.amount * 100).to_i')
    expect(generated).to include("type: 'sbp'")
    expect(generated).to include("operation.payout_requisite.dig('sbp', 'phone')")
  end

  it 'renders verify_signature! with the HMAC-SHA256 primitive' do
    expect(generated).to include('def verify_signature!(payload)')
    expect(generated).to include("OpenSSL::HMAC.hexdigest('SHA256'")
    expect(generated).to include("credentials.fetch('callback_secret')")
  end

  it 'matches the snapshot fixture' do
    expected = File.read(File.join(SpecPaths::FIXTURES, 'expected_novapay_service.rb'))
    # The header carries provenance stamps (generator version, timestamp,
    # spec SHA256) that legitimately vary run-to-run. Normalize them out
    # before comparing — the rest of the file must be byte-identical.
    expect(normalize_provenance(generated)).to eq(normalize_provenance(expected))
  end

  def normalize_provenance(src)
    src
      .sub(/^# Auto-generated by `integrate` v\S+ at \S+\.$/, '# Auto-generated by `integrate` v<VER> at <TS>.')
      .sub(/^# Source spec:  \S.*$/, '# Source spec:  <PATH>')
      .sub(/^# Spec sha256:  \S+$/, '# Spec sha256:  <SHA>')
      .sub(/^# Rules file:   \S.*$/, '# Rules file:   <PATH>')
      .sub(/^# Rules sha256: \S+$/, '# Rules sha256: <SHA>')
  end

  it 'raises SpecInvalid when no create endpoint is present' do
    endpoints = spec.endpoints.reject { |ep| ep.role == :create }
    trimmed = spec.with(endpoints: endpoints)
    expect { described_class.new(trimmed).call }
      .to raise_error(Integrate::Errors::SpecInvalid, /No POST endpoint/)
  end
end
