# frozen_string_literal: true

require 'spec_helper'

RSpec.describe Integrate::Generator::Service, 'PayCloud snapshot' do
  let(:paycloud_spec) { File.join(SpecPaths::ROOT, 'examples', 'paycloud_api.yaml') }
  let(:expected) { File.read(File.join(SpecPaths::FIXTURES, 'expected_paycloud_service.rb')) }
  let(:spec) { Integrate::Parser::OpenApi.new(paycloud_spec).parse }
  let(:generated) { described_class.new(spec).call }

  it 'matches the golden fixture (regenerate on intentional change)' do
    if ENV['REGENERATE_SNAPSHOT']
      File.write(File.join(SpecPaths::FIXTURES, 'expected_paycloud_service.rb'), generated)
      skip 'regenerated snapshot'
    end
    # Provenance stamps (version, timestamp, SHA256) legitimately vary — normalize before diff.
    expect(normalize_provenance(generated)).to eq(normalize_provenance(expected))
  end

  def normalize_provenance(src)
    src
      .sub(/^# Auto-generated by `integrate` v\S+ at \S+\.$/, '# Auto-generated by `integrate` v<VER> at <TS>.')
      .sub(/^# Source spec:  \S.*$/, '# Source spec:  <PATH>')
      .sub(/^# Spec sha256:  \S+$/, '# Spec sha256:  <SHA>')
      .sub(/^# Rules file:   \S.*$/, '# Rules file:   <PATH>')
      .sub(/^# Rules sha256: \S+$/, '# Rules sha256: <SHA>')
  end

  it 'produces syntactically valid Ruby' do
    require 'tempfile'
    Tempfile.create(['pay', '.rb']) do |f|
      f.write(generated)
      f.flush
      stderr = `ruby -c #{f.path} 2>&1`
      expect(stderr).to include('Syntax OK')
    end
  end
end
