# frozen_string_literal: true

# Auto-generated by `integrate` v0.1.0 at 2026-09-06T08:34:19Z.
# Source spec:  tasks/provider_api.yaml
# Spec sha256:  415f50ee36fb331dfab49ceed0e8ed3b0ebe16053d7e00dbabd32282f4396551
#
# Do not edit by hand — regenerate from the OpenAPI spec instead:
#   bin/integrate generate --spec <spec.yaml> --provider <slug> [--rules overrides.yaml]
#
# NOTE: this file is NOT standalone-runnable. It inherits from
# `Provider::BaseService`, which lives in the Space Payments host application.
# Trying `ruby <this file>` will fail with `uninitialized constant BaseService`.
# To smoke-test locally, run:
#   bin/integrate verify <path-to-this-file>
# (uses spec/support/provider_base_stub.rb to satisfy the contract).
#
# Provider: NovaPay Payout API
# Contract: Provider::BaseService (create_request / fetch_status /
#           process_callback / check_conditions).
class Provider
  class NovapayService < BaseService
    BASE_URL = ENV.fetch('NOVAPAY_BASE_URL', 'https://api.sandbox.novapay.example/v1')

    STATUS_MAP = {
      'pending' => 'in_progress',
      'processing' => 'in_progress',
      'completed' => 'approved',
      'failed' => 'rejected',
      'cancelled' => 'rejected',
    }.freeze

    ERROR_MAP = {
      400 => 'validation_error',
      401 => 'invalid_credentials',
      402 => 'insufficient_balance',
      404 => 'not_found',
      409 => 'duplicate',
      422 => 'validation_error',
      429 => 'rate_limit',
      500 => 'internal_error',
    }.freeze

    PROVIDER_ERROR_MAP = {
      'validation_error' => 'validation_error',
      'insufficient_balance' => 'insufficient_balance',
      'recipient_not_found' => 'recipient_not_found',
      'bank_unavailable' => 'bank_unavailable',
      'amount_limit_exceeded' => 'amount_limit_exceeded',
      'rate_limit_exceeded' => 'rate_limit',
      'internal_error' => 'internal_error',
      'unauthorized' => 'invalid_credentials',
      'not_found' => 'not_found',
      'invalid_status' => 'invalid_status',
    }.freeze

    def create_request(operation, request_method = 'create')
      payload = build_payout_payload(operation)
      headers = auth_headers.merge('Idempotency-Key' => idempotency_key_for(operation))
      response = client.post("#{BASE_URL}/payouts", json: payload, headers: headers)
      parse_create_response(operation, response)
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    def fetch_status(operation)
      response = client.get("#{BASE_URL}/payouts/#{operation.provider_operation_id}", headers: auth_headers)
      return 'in_progress' if response.status.to_i == 404

      map_status(response.body['status'])
    end

    def cancel_request(operation)
      response = client.post("#{BASE_URL}/payouts/#{operation.provider_operation_id}/cancel", headers: auth_headers)
      case response.status.to_i
      when 200, 204
        success(response.body)
      when 409
        failure(:conflict, "provider.#{response.body.dig('error', 'code') || 'invalid_status'}")
      else
        error_key = ERROR_MAP.fetch(response.status.to_i, 'internal_error')
        failure(status_sym_for(response.status.to_i), "provider.#{error_key}")
      end
    rescue Provider::RateLimitError
      failure(:too_many_requests, 'provider.rate_limit')
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    end

    # Webhook signature: X-NovaPay-Signature
    # Algorithm: hmac_sha256 (hex).
    def process_callback(payload)
      verify_signature!(payload)

      # Support both `event` (NovaPay-style: 'payout.completed') and `type`
      # (PayCloud/Stripe-style: 'transfer.settled') as the event discriminator.
      event = payload['event'] || payload['type']

      case event
      when /completed$|settled$|paid$|succeeded$/
        approve_operation(payload['payout_id'])
      when /failed$|declined$|rejected$/
        reject_operation(payload['payout_id'], payload.dig('error', 'code') || payload.dig('problem', 'type'))
      when /cancelled$|canceled$|voided$/
        reject_operation(payload['payout_id'], 'cancelled')
      when /processing$|sent$|queued$/
        success
      else
        failure(:unprocessable_entity, 'unknown_event')
      end
    end

    # Helper method, NOT part of Provider::BaseService contract.
    # Returns raw balance payload from provider (amounts in minor units).
    def fetch_balance
      response = client.get("#{BASE_URL}/balance", headers: auth_headers)
      response.body
    end

    def check_conditions(operation, request_method)
      base_result = super
      return base_result if base_result.failed?

      # Provider requires minimum amount of 100000 minor units
      # (= 1000 in major units — see OpenAPI 'minimum').
      return failure(:unprocessable_entity, 'amount_too_low') if operation.amount < 1000
      success
    end

    def map_status(provider_status)
      STATUS_MAP.fetch(provider_status.to_s, 'in_progress')
    end

    private

    def build_payout_payload(operation)
      payload = {
        # amount in minor units (kopecks)
        amount: (operation.amount * 100).to_i,
        currency: 'RUB',
        external_id: operation.id,
        recipient: {
          type: 'sbp',
          phone: operation.payout_requisite.dig('sbp', 'phone'),
          bank_code: operation.payout_requisite.dig('sbp', 'bank_code'),
          bank_name: operation.payout_requisite.dig('sbp', 'bank_name')
        }
      }
      payload
    end

    # No mutation of `operation` — the platform reads the returned payload
    # (`success.payload['id']`) and persists the provider id itself.
    def parse_create_response(_operation, response)
      case response.status.to_i
      when 200, 201
        success(response.body)
      when 409
        # Idempotent duplicate — treat as success; body contains the existing
        # payout with its `id`.
        success(response.body)
      else
        error_key = provider_error_key(response) || ERROR_MAP.fetch(response.status.to_i, 'internal_error')
        failure(status_sym_for(response.status.to_i), "provider.#{error_key}")
      end
    end

    def provider_error_key(response)
      return nil unless response.body.is_a?(Hash)

      code = response.body.dig('error', 'code')
      return nil unless code

      PROVIDER_ERROR_MAP[code.to_s]
    end

    def status_sym_for(http_code)
      {
        200 => :ok, 201 => :created, 202 => :accepted, 204 => :no_content,
        400 => :bad_request, 401 => :unauthorized, 402 => :payment_required,
        403 => :forbidden, 404 => :not_found, 409 => :conflict,
        422 => :unprocessable_entity, 429 => :too_many_requests,
        500 => :internal_server_error, 502 => :bad_gateway,
        503 => :service_unavailable, 504 => :gateway_timeout
      }[http_code.to_i] || :internal_server_error
    end

    def idempotency_key_for(operation)
      require 'securerandom'
      # Stable per-operation key: retries hit the same server-side idempotency
      # record, preventing double payouts.
      key = operation.respond_to?(:idempotency_key) ? operation.idempotency_key : nil
      key || "op-#{operation.id}"
    end

    def auth_headers
      { 'X-API-Key' => credentials.fetch('api_key') }
    end

    # Verify HMAC-SHA256 signature over the raw webhook body.
    #
    # `payload` is the already-parsed JSON body of the webhook. The signature
    # header value and the raw request body must be enriched by the calling
    # controller under conventional keys:
    #
    #   payload['_signature'] — value of the `X-NovaPay-Signature` header.
    #   payload['_raw_body']  — request.raw_post (byte-identical HTTP body).
    #
    # `_raw_body` is REQUIRED for byte-identical HMAC — JSON.dump(payload) would
    # differ from the provider's body by key ordering and whitespace.
    def verify_signature!(payload)
      require 'openssl'
      require 'json'

      signature = payload['_signature'] || payload['signature']
      raw       = payload['_raw_body'] ||
                  raise(Provider::UnauthorizedError,
                        'raw HTTP body missing: controller must enrich payload with `_raw_body`')
      expected  = OpenSSL::HMAC.hexdigest('SHA256', credentials.fetch('callback_secret'), raw)

      return if secure_compare(expected, signature.to_s)

      raise Provider::UnauthorizedError, 'Invalid webhook signature'
    end

    def secure_compare(left, right)
      return false if left.bytesize != right.bytesize

      if defined?(Rack::Utils)
        Rack::Utils.secure_compare(left, right)
      else
        OpenSSL.fixed_length_secure_compare(left, right)
      end
    end
  end
end
